# Generated by Django 3.0.4 on 2020-04-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crystal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('properties', models.TextField(max_length=250)),
                ('meaning', models.TextField(max_length=250)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
