# Generated by Django 3.0.4 on 2020-04-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleansing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wellness', models.TextField(max_length=50)),
                ('meaning', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cleansing',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='crystal',
            name='properties',
        ),
        migrations.AlterField(
            model_name='cleansing',
            name='cleanse',
            field=models.CharField(choices=[('S', 'SUNLIGHT'), ('D', 'MOONLIGHT'), ('H', 'HELD')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='cleansing',
            name='date',
            field=models.DateField(verbose_name='cleansing date'),
        ),
        migrations.AddField(
            model_name='crystal',
            name='energys',
            field=models.ManyToManyField(to='main_app.Energy'),
        ),
    ]
